# Generated by Django 5.1.3 on 2025-01-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
