# Generated by Django 5.1.3 on 2025-01-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishs', '0002_alter_reg_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='email',
            new_name='ko',
        ),
    ]
