# Generated by Django 5.1.3 on 2025-01-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishs', '0004_rename_ko_reg_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='password',
        ),
    ]
