# Generated by Django 5.1.3 on 2025-01-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishs', '0005_remove_reg_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='image',
            field=models.ImageField(default='null', upload_to='image'),
            preserve_default=False,
        ),
    ]
