# Generated by Django 5.1.3 on 2025-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishs', '0006_reg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
